
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://devServer:3306/wol
    username: root
    password: AwUr85QF3w1kpim5NMvMOt5pR/8r5H3NNRcU0IgcpOlSSXXeG3VVyZ6lEM8NmP90svJnQX2nTxRKTlbPv4Y3QA==
    driver-class-name: org.mariadb.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      db-type: mariadb
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 5000
      keep-alive: true
      filter:
        config:
          enabled: true
        stat:
          enabled: true
          db-type: mariadb
          log-slow-sql: true
          slow-sql-millis: 2000
      web-stat-filter:
        enabled: true
        exclusions:
        - "*.js"
        - "*.gif"
        - "*.jpg"
        - "*.png"
        - "*.css"
        - "*.ico"
        - "/druid/*"
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: admin
        allow:
      remove-abandoned: false
      test-while-idle: true
      connection-properties: config.decrypt=true;config.decrypt.key=${db-public-key}
  jpa:
    database: mysql
    database-platform: mysql
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB103Dialect
  redis:
    host: devServer
    port: 6379
    password:
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
    database: 0
  output:
    ansi:
      enabled: always
  mvc:
    servlet:
      load-on-startup: 1
    converters:
      preferred-json-mapper: gson
server:
  port: 8080
logging:
  config: classpath:log4j2/log4j2-prod.xml
mybatis:
  type-aliases-package: cn.lemongo97.wol.model
mybatis-plus:
  type-enums-package: cn.lemongo97.wol.common
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    banner: false
  type-aliases-package: cn.lemongo97.wol.model
  mapper-locations: classpath*:mybatis/mapper/*.xml

db-public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBANy4Fa57NEkscuGtitgoCyMtfSmHAlS4e99LR4+v6gRq9gqpVxgVHYd+WSl3aqf8tZFnU8QKY2iF92E5vGfeUXECAwEAAQ==
